# config.yml
chunking:
  strategy: "normal"
  chunk_size: 300
  chunk_overlap: 20

tech_specialties:
  - "software engineer"
  - "data scientist"
  - "cybersecurity analyst"
  - "AI engineer"
  - "cloud engineer"
  - "devops engineer"
  - "UI/UX designer"
  - "full stack developer"
  - "mobile app developer"
  - "machine learning engineer"

locations:
  USA: "San Francisco, CA"
  UK: "London, England"
  France: "Paris, France"

server:
  hostname: "localhost"
  port: 8080
  persistence_path: "./weaviate_data"

models:
  llm: "llama-3.3-70b-versatile"
  embedding: "BAAI/bge-small-en-v1.5"

vector_store:
  index_name: "JobPosts"
  persistence_path: "./weaviate_data"

ranking:
  top_n: 2
  model: "BAAI/bge-reranker-base"

retrieval:
  similarity_top_k: 5
  vector_store_query_mode: "hybrid"
  alpha: 0.5

data:
  csv_path: "../data/tech_jobs_dataset.csv"
  

api:
  hostname: "0.0.0.0"
  port: 8000   # FastAPI app